"""fix permission model

Revision ID: 08298f023253
Revises: f7d9cff6beb1
Create Date: 2024-03-31 16:00:42.174254

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '08298f023253'
down_revision = 'f7d9cff6beb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('permissions', 'can_grant',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('permissions', 'can_grant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('permissions', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
