"""unique posts.id

Revision ID: 2d7d002cb6be
Revises: e1f15fd2ea7f
Create Date: 2024-04-01 21:10:24.452968

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2d7d002cb6be'
down_revision = 'e1f15fd2ea7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'posts', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
