"""Removed revision id

Revision ID: 4ca5fa60e2ed
Revises: 4f047c0efc09
Create Date: 2024-04-02 11:18:36.545775

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4ca5fa60e2ed'
down_revision = '4f047c0efc09'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'revision_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('revision_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
