"""rename id to telegram_id

Revision ID: 4f244baf7b4f
Revises: 605c291b7a08
Create Date: 2024-04-02 14:38:45.608211

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import Sequence

# revision identifiers, used by Alembic.
revision = '4f244baf7b4f'
down_revision = '605c291b7a08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM post_channel_bindings")
    op.execute("DELETE FROM channels")
    op.execute("CREATE SEQUENCE IF NOT EXISTS channels_id_seq START 1")
    op.add_column('channels', sa.Column('telegram_id', sa.BigInteger(), nullable=False))
    op.alter_column('channels', 'id',
                    existing_type=sa.BIGINT(),
                    type_=sa.Integer(),
                    existing_nullable=False,
                    autoincrement=True,
                    server_default=Sequence('channels_id_seq').next_value())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'id',
                    existing_type=sa.Integer(),
                    type_=sa.BIGINT(),
                    existing_nullable=False,
                    autoincrement=True)
    op.drop_column('channels', 'telegram_id')
    # ### end Alembic commands ###
