"""Changed channel model

Revision ID: 546e33237a7f
Revises: 8c364518c7ad
Create Date: 2024-03-31 16:38:56.301168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '546e33237a7f'
down_revision = '8c364518c7ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['organization_bots.bot_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    op.drop_table('bot_channels')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_channels',
    sa.Column('bot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('channel_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['organization_bots.bot_id'], name='bot_channels_bot_id_fkey'),
    sa.PrimaryKeyConstraint('channel_id', name='bot_channels_pkey')
    )
    op.drop_table('channels')
    # ### end Alembic commands ###
