"""add next_run_delta to task

Revision ID: 56767749b9fa
Revises: 33d8f821bf00
Create Date: 2024-04-02 15:27:39.412786

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '56767749b9fa'
down_revision = '33d8f821bf00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_run_delta', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'next_run_delta')
    # ### end Alembic commands ###
