"""add telegram_message_id to post

Revision ID: 605c291b7a08
Revises: 3ac53831d12c
Create Date: 2024-04-02 13:08:04.264163

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '605c291b7a08'
down_revision = '3ac53831d12c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_post_channel_bindings_uc', 'post_channel_bindings', ['post_id', 'channel_id'])
    op.add_column('posts', sa.Column('telegram_message_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'telegram_message_id')
    op.drop_constraint('_post_channel_bindings_uc', 'post_channel_bindings', type_='unique')
    # ### end Alembic commands ###
