"""add planned_time to task model

Revision ID: 8b049d8157b8
Revises: e5ba622f6291
Create Date: 2024-04-01 14:01:48.061618

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8b049d8157b8'
down_revision = 'e5ba622f6291'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('planned_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'planned_time')
    # ### end Alembic commands ###
