"""Added bots2organization + channels2bots models

Revision ID: 8c364518c7ad
Revises: 43d34a4dc3e9
Create Date: 2024-03-31 16:33:38.277104

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '8c364518c7ad'
down_revision = '43d34a4dc3e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_bots',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('bot_token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('bot_id')
    )
    op.create_table('bot_channels',
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['organization_bots.bot_id'], ),
    sa.PrimaryKeyConstraint('channel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_channels')
    op.drop_table('organization_bots')
    # ### end Alembic commands ###
