"""add updated_at to post

Revision ID: 9651dea19b1a
Revises: 56767749b9fa
Create Date: 2024-04-02 16:24:33.561682

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '9651dea19b1a'
down_revision = '56767749b9fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'updated_at')
    # ### end Alembic commands ###
