"""add planned_time and sent_status to post model

Revision ID: b8c85cb21aa0
Revises: a21bb9142394
Create Date: 2024-04-01 18:04:56.643721

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'b8c85cb21aa0'
down_revision = 'a21bb9142394'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('planned_time', sa.DateTime(), nullable=True))
    enum_type = sa.Enum('NOT_READY', 'TIME_NOT_ENTERED', 'WAITING', 'SENT_OK', 'SENT_ERROR', name='sentstatus')
    op.create_table(
        '_dummy',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('status', enum_type)
    )
    op.drop_table('_dummy')
    op.add_column('posts', sa.Column('sent_status', enum_type, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sent_status')
    op.drop_column('posts', 'planned_time')
    # ### end Alembic commands ###
