"""Fixed unique description

Revision ID: dc52d41545c3
Revises: da60a736986b
Create Date: 2024-03-31 23:46:43.955538

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'dc52d41545c3'
down_revision = 'da60a736986b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('organizations_description_key', 'organizations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('organizations_description_key', 'organizations', ['description'])
    # ### end Alembic commands ###
