"""Added revision as primary key

Revision ID: e16f7a2a95f1
Revises: b8c85cb21aa0
Create Date: 2024-04-01 18:38:56.116771

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e16f7a2a95f1'
down_revision = 'b8c85cb21aa0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute('ALTER TABLE posts DROP CONSTRAINT posts_pkey CASCADE')
    op.create_primary_key('posts_pkey', 'posts', ['id', 'revision_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
