"""add unique constraint to channel.id

Revision ID: e1f15fd2ea7f
Revises: e16f7a2a95f1
Create Date: 2024-04-01 20:59:30.050592

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1f15fd2ea7f'
down_revision = 'e16f7a2a95f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'channels', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
