"""add organization_stop_toggles

Revision ID: e7d8d0558eb8
Revises: f9a67c1b118c
Create Date: 2024-04-02 21:25:06.363333

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e7d8d0558eb8'
down_revision = 'f9a67c1b118c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_stop_toggles',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_stop_toggles')
    # ### end Alembic commands ###
