"""Post model added

Revision ID: ebe590969bac
Revises: 546e33237a7f
Create Date: 2024-03-31 17:02:04.944266

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ebe590969bac'
down_revision = '546e33237a7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Enum('OPEN', 'WAITING', 'REJECTED', 'APPROVED', name='status'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('channels', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('channels', 'channel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('channel_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'id')
    op.drop_table('posts')
    # ### end Alembic commands ###
