"""create dbsentpostinfo

Revision ID: ee9179c37c20
Revises: 9651dea19b1a
Create Date: 2024-04-02 20:26:44.702276

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ee9179c37c20'
down_revision = '9651dea19b1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_post_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('chat_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id', 'post_id', 'channel_id'),
    sa.UniqueConstraint('id')
    )
    op.drop_column('posts', 'telegram_message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('telegram_message_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_table('sent_post_info')
    # ### end Alembic commands ###
